### ISSUE TITLE
ClientBuilder isn't available in "0.1.4"

### ISSUE THREAD

**Issue by sharunkumar** [jesopo/bisky#3]
I know this is a w.i.p but would it be possible to publish a beta version with the current state of the mater branch?

**Comment by jesopo** [comment]
i've just published v0.2.1, does that work?

**Comment by sharunkumar** [comment]
thank you! it works now

**Comment by sharunkumar** [comment]
![image](https://github.com/jesopo/bisky/assets/715417/4f9b07b8-6c2f-4a83-81bf-ff703ca2b383)

not sure why it shows like this in VSCode, though

**Comment by jesopo** [comment]
cache?

**Comment by sharunkumar** [comment]
Not sure, I'm able to build with the version, maybe its just an issue with the extension
